spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: api-route
          uri: http://localhost:8080/api
          predicates:
            - Path=/api/**
          filters:
            - JwtAuthenticationFilter