apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: kwt-development
spec:
  replicas: 1
  selector:
    matchLabels:
      project: kwt
      app: gateway
      env: development
  template:
    metadata:
      labels:
        project: kwt
        app: gateway
        env: development
    spec:
      containers:
        - name: gateway
          image: wondookong/kwt-development-gateway:latest
          ports:
            - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
