apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: kwt-dev
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway-dev
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: k8s-kwt
    app.kubernetes.io/managed-by: kubectl
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/instance: api-gateway-dev
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: k8s-kwt
      env: dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/instance: api-gateway-dev
        app.kubernetes.io/version: v1.0.0
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: k8s-kwt
        app.kubernetes.io/managed-by: kubectl
        env: dev
    spec:
      containers:
        - name: api-gateway
          image: wondookong/kwt-dev-gateway:latest
          ports:
            - containerPort: 8080
#          startupProbe:
#            httpGet:
#              path: "/startup"
#              port: 8080
#            periodSeconds: 5
#            failureThreshold: 36
#          readinessProbe:
#            httpGet:
#              path: "/readiness"
#              port: 8080
#            periodSeconds: 10
#            failureThreshold: 3
#          livenessProbe:
#            httpGet:
#              path: "/liveness"
#              port: 8080
#            periodSeconds: 10
#            failureThreshold: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
