apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: kwt-prod
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway-prod
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: k8s-kwt
    app.kubernetes.io/managed-by: kubectl
    env: prod
spec:
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway-prod
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: k8s-kwt
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
