apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: kwt-production
spec:
  selector:
    project: kwt
    app: gateway
    env: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
